SECTIONS_API = "http://sbornikbackend.somee.com/MainSections"
ARTICLE_API = "http://sbornikbackend.somee.com/GuideSections"
FACULTIES_API = "http://sbornikbackend.somee.com/Faculties"
FACULTIES_INFO_API = "http://sbornikbackend.somee.com/FacultiesInfo"
FACULTIES_INFO_ID = "http://sbornikbackend.somee.com/FacultiesInfoId"
CONTACTS_API="http://sbornikbackend.somee.com/Contacts"
TOKEN_API = "http://sbornikbackend.somee.com/Token"
USER_API = "http://sbornikbackend.somee.com/UsersDesktop"