# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt


class Section(QPushButton):
    def __init__(self, img_path="../../Users/caisilus/Pictures/Saved Pictures/S8HLlscvIvk.jpg", section_name="section name"):
        QPushButton.__init__(self, parent=None)
        #self.w = QWidget()
        #self.w.setGeometry(QtCore.QRect(30, 30, 471, 231))
        #self.frame.setObjectName("frame")
        layout = QHBoxLayout()
        self.setLayout(layout)
        self.setMaximumHeight(200)
        self.setMinimumHeight(140)

        label = QtWidgets.QLabel(self)
        #self.label.setGeometry(QtCore.QRect(40, 50, 151, 141))
        label.setMaximumHeight(120)
        label.setMaximumWidth(120)
        label.setText("")
        label.setPixmap(QtGui.QPixmap(img_path))
        label.setScaledContents(True)
        label.setObjectName("label")
        layout.addWidget(label)
        #layout.addStretch(1)

        label_2 = QtWidgets.QLabel(self)
        #self.label_2.setGeometry(QtCore.QRect(220, 60, 241, 101))
        label_2.setMinimumHeight(120)
        font = QtGui.QFont()
        font.setPointSize(14)
        label_2.setFont(font)
        label_2.setText(section_name)
        label_2.setAutoFillBackground(False)
        label_2.setTextFormat(QtCore.Qt.AutoText)
        label_2.setScaledContents(False)
        label_2.setObjectName("label_2")
        layout.addWidget(label_2)


class SectionsWindow(QMainWindow, QWidget):
    def __init__(self):
        super(SectionsWindow, self).__init__()
        self.resize(800, 600)

        widget = QWidget()
        layout = QVBoxLayout()
        self.section1 = Section(section_name="section1")
        self.section2 = Section(section_name="section2")
        self.section3 = Section(section_name="section3")
        layout.addWidget(self.section1)
        #self.layout.addStretch(1)
        layout.addWidget(self.section2)
        #self.layout.addStretch(1)
        layout.addWidget(self.section3)     
        #self.layout.addStretch()
        widget.setLayout(layout)
        #scroller_layout = QVBoxLayout()
        #scroller_layout.addLayout(layout)
        #scroller_layout.addStretch()
        #widget.setLayout(scroller_layout)

        self.scroller = QScrollArea()
        #self.setCentralWidget(self.scroller)
        self.scroller.setFixedWidth(700)
        self.scroller.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scroller.setWidgetResizable(True)
        
        self.scroller.setWidget(widget)
        #self.scroller.adjustSize()

        main_layout = QVBoxLayout()
        main_layout.addWidget(self.scroller)
        #main_layout.addStretch()
        self.main_widget = QWidget()
        self.main_widget.setLayout(main_layout)
        self.setCentralWidget(self.main_widget)
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = SectionsWindow()
    MainWindow.show()
    sys.exit(app.exec_())
